# Makefile.in generated by automake 1.10.2 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/Iris
pkglibdir = $(libdir)/Iris
pkgincludedir = $(includedir)/Iris
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = simMc2Mesh$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(noinst_HEADERS) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(srcdir)/config.h.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
LIBRARIES = $(noinst_LIBRARIES)
AR = ar
ARFLAGS = cru
libIris_a_AR = $(AR) $(ARFLAGS)
libIris_a_LIBADD =
am__objects_1 = libIris_a-link.$(OBJEXT) libIris_a-simulator.$(OBJEXT) \
	libIris_a-component.$(OBJEXT) libIris_a-irisEvent.$(OBJEXT) \
	libIris_a-flit.$(OBJEXT) libIris_a-util.$(OBJEXT) \
	libIris_a-highLevelPacket.$(OBJEXT) \
	libIris_a-lowLevelPacket.$(OBJEXT) libIris_a-router.$(OBJEXT) \
	libIris_a-processor.$(OBJEXT) libIris_a-interface.$(OBJEXT) \
	libIris_a-irisLink.$(OBJEXT) \
	libIris_a-networkComponent.$(OBJEXT) \
	libIris_a-genericBuffer.$(OBJEXT) \
	libIris_a-genericRC.$(OBJEXT) \
	libIris_a-genericCrossbar.$(OBJEXT) \
	libIris_a-genericInterface.$(OBJEXT) \
	libIris_a-genericData.$(OBJEXT) \
	libIris_a-genericLink.$(OBJEXT) libIris_a-ptop_swa.$(OBJEXT) \
	libIris_a-genericRouterNoVcs.$(OBJEXT) \
	libIris_a-genericRouterVct.$(OBJEXT) \
	libIris_a-genericFlatMc.$(OBJEXT) \
	libIris_a-genericTPG.$(OBJEXT) libIris_a-mshr.$(OBJEXT) \
	libIris_a-request.$(OBJEXT) libIris_a-mesh.$(OBJEXT)
am_libIris_a_OBJECTS = $(am__objects_1)
libIris_a_OBJECTS = $(am_libIris_a_OBJECTS)
am__installdirs = "$(DESTDIR)$(bindir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am_simMc2Mesh_OBJECTS = simMc2Mesh-simMc2Mesh.$(OBJEXT)
simMc2Mesh_OBJECTS = $(am_simMc2Mesh_OBJECTS)
simMc2Mesh_DEPENDENCIES = libIris.a
simMc2Mesh_LINK = $(CXXLD) $(simMc2Mesh_CXXFLAGS) $(CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
SOURCES = $(libIris_a_SOURCES) $(simMc2Mesh_SOURCES)
DIST_SOURCES = $(libIris_a_SOURCES) $(simMc2Mesh_SOURCES)
HEADERS = $(noinst_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/mitch/workspace/iris_phy_router/missing --run aclocal-1.10
AMTAR = ${SHELL} /home/mitch/workspace/iris_phy_router/missing --run tar
AUTOCONF = ${SHELL} /home/mitch/workspace/iris_phy_router/missing --run autoconf
AUTOHEADER = ${SHELL} /home/mitch/workspace/iris_phy_router/missing --run autoheader
AUTOMAKE = ${SHELL} /home/mitch/workspace/iris_phy_router/missing --run automake-1.10
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/mitch/workspace/iris_phy_router/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = Iris
PACKAGE_BUGREPORT = mitchelle dot rasquinha at gatech.edu
PACKAGE_NAME = iris
PACKAGE_STRING = iris 0.1
PACKAGE_TARNAME = iris
PACKAGE_VERSION = 0.1
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.0
abs_builddir = /home/mitch/workspace/iris_phy_router
abs_srcdir = /home/mitch/workspace/iris_phy_router
abs_top_builddir = /home/mitch/workspace/iris_phy_router
abs_top_srcdir = /home/mitch/workspace/iris_phy_router
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /home/mitch/workspace/iris_phy_router/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
noinst_LIBRARIES = libIris.a
OBJDIR = $(TOPDIR)/build
BUILDDIR = $(TOPDIR)/build
CXX_FLAGS = -D_STLP_DEBUG -I source -pthread -ansi -Wall -g -gstabs+ -O3 -funroll-loops -fkeep-inline-functions -fpermissive
#DEBUG_FLAGS = -D_DEBUG -D_DEBUG_ROUTER 
DEBUG_FLAGS = -D_DEBUG -DDEBUG -D_DEBUG_ROUTER -D_DEBUG_INTERFACE #-fprofile-arcs -ftest-coverage
IRIS_SOURCES = \
		  source/kernel/link.cc \
		  source/kernel/simulator.cc \
		  source/kernel/component.cc \
		  source/data_types/impl/irisEvent.cc \
		  source/data_types/impl/flit.cc \
		  source/data_types/impl/util.cc \
		  source/data_types/impl/highLevelPacket.cc \
		  source/data_types/impl/lowLevelPacket.cc \
		  source/components/interfaces/router.cc \
		  source/components/interfaces/processor.cc \
		  source/components/interfaces/interface.cc \
		  source/components/interfaces/irisLink.cc \
		  source/components/interfaces/networkComponent.cc \
		  source/components/impl/genericBuffer.cc \
		  source/components/impl/genericRC.cc \
		  source/components/impl/genericCrossbar.cc \
		  source/components/impl/genericInterface.cc \
		  source/components/impl/genericData.cc \
		  source/components/impl/genericLink.cc \
		  source/components/impl/ptop_swa.cc \
		  source/components/impl/genericRouterNoVcs.cc \
		  source/components/impl/genericRouterVct.cc \
		  source/components/impl/genericFlatMc.cc \
		  source/components/impl/genericTPG.cc \
		  source/memctrl/mshr.cc \
		  source/memctrl/request.cc \
		  source/frontend/impl/mesh.cc 

simMc2Mesh_CXXFLAGS = $(CXX_FLAGS)
simMc2Mesh_SOURCES = \
	       source/frontend/impl/simMc2Mesh.cc

simMc2Mesh_LDADD = libIris.a
libIris_a_CXXFLAGS = $(CXX_FLAGS)
libIris_a_SOURCES = $(IRIS_SOURCES)
noinst_HEADERS = \
		 source/kernel/simulator.h \
		 source/kernel/link.h \
		 source/kernel/component.h \
		 source/data_types/impl/irisEvent.h \
		 source/data_types/impl/flit.h \
		 source/data_types/impl/util.h \
		 source/data_types/impl/highLevelPacket.h \
		 source/data_types/impl/lowLevelPacket.h \
		 source/components/interfaces/crossbar.h \
		 source/components/interfaces/addressDecoder.h \
		 source/components/interfaces/interface.h \
		 source/components/interfaces/buffer.h \
		 source/components/interfaces/genericComponentHeader.h \
		 source/components/interfaces/virtualChannelArbiter.h \
		 source/components/interfaces/router.h \
		 source/components/interfaces/portArbiter.h \
		 source/components/interfaces/processor.h \
		 source/components/interfaces/irisLink.h \
		 source/components/interfaces/networkComponent.h \
		 source/components/impl/genericRC.h \
		 source/components/impl/genericCrossbar.h \
		 source/components/impl/genericBuffer.h \
		 source/components/impl/genericInterface.h \
		 source/components/impl/genericLink.h \
		 source/components/impl/ptop_swa.h \
		 source/components/impl/genericRouterNoVcs.h \
		 source/components/impl/genericRouterVct.h \
		 source/components/impl/genericTPG.h \
		 source/components/impl/genericFlatMc.h \
		 source/frontend/impl/mesh.h \
		 source/tests/clock.h \
		 source/memctrl/mshr.h \
		 source/memctrl/request.h 

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cc .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
libIris.a: $(libIris_a_OBJECTS) $(libIris_a_DEPENDENCIES) 
	-rm -f libIris.a
	$(libIris_a_AR) libIris.a $(libIris_a_OBJECTS) $(libIris_a_LIBADD)
	$(RANLIB) libIris.a
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
simMc2Mesh$(EXEEXT): $(simMc2Mesh_OBJECTS) $(simMc2Mesh_DEPENDENCIES) 
	@rm -f simMc2Mesh$(EXEEXT)
	$(simMc2Mesh_LINK) $(simMc2Mesh_OBJECTS) $(simMc2Mesh_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/libIris_a-component.Po
include ./$(DEPDIR)/libIris_a-flit.Po
include ./$(DEPDIR)/libIris_a-genericBuffer.Po
include ./$(DEPDIR)/libIris_a-genericCrossbar.Po
include ./$(DEPDIR)/libIris_a-genericData.Po
include ./$(DEPDIR)/libIris_a-genericFlatMc.Po
include ./$(DEPDIR)/libIris_a-genericInterface.Po
include ./$(DEPDIR)/libIris_a-genericLink.Po
include ./$(DEPDIR)/libIris_a-genericRC.Po
include ./$(DEPDIR)/libIris_a-genericRouterNoVcs.Po
include ./$(DEPDIR)/libIris_a-genericRouterVct.Po
include ./$(DEPDIR)/libIris_a-genericTPG.Po
include ./$(DEPDIR)/libIris_a-highLevelPacket.Po
include ./$(DEPDIR)/libIris_a-interface.Po
include ./$(DEPDIR)/libIris_a-irisEvent.Po
include ./$(DEPDIR)/libIris_a-irisLink.Po
include ./$(DEPDIR)/libIris_a-link.Po
include ./$(DEPDIR)/libIris_a-lowLevelPacket.Po
include ./$(DEPDIR)/libIris_a-mesh.Po
include ./$(DEPDIR)/libIris_a-mshr.Po
include ./$(DEPDIR)/libIris_a-networkComponent.Po
include ./$(DEPDIR)/libIris_a-processor.Po
include ./$(DEPDIR)/libIris_a-ptop_swa.Po
include ./$(DEPDIR)/libIris_a-request.Po
include ./$(DEPDIR)/libIris_a-router.Po
include ./$(DEPDIR)/libIris_a-simulator.Po
include ./$(DEPDIR)/libIris_a-util.Po
include ./$(DEPDIR)/simMc2Mesh-simMc2Mesh.Po

.cc.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

libIris_a-link.o: source/kernel/link.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-link.o -MD -MP -MF $(DEPDIR)/libIris_a-link.Tpo -c -o libIris_a-link.o `test -f 'source/kernel/link.cc' || echo '$(srcdir)/'`source/kernel/link.cc
	mv -f $(DEPDIR)/libIris_a-link.Tpo $(DEPDIR)/libIris_a-link.Po
#	source='source/kernel/link.cc' object='libIris_a-link.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-link.o `test -f 'source/kernel/link.cc' || echo '$(srcdir)/'`source/kernel/link.cc

libIris_a-link.obj: source/kernel/link.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-link.obj -MD -MP -MF $(DEPDIR)/libIris_a-link.Tpo -c -o libIris_a-link.obj `if test -f 'source/kernel/link.cc'; then $(CYGPATH_W) 'source/kernel/link.cc'; else $(CYGPATH_W) '$(srcdir)/source/kernel/link.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-link.Tpo $(DEPDIR)/libIris_a-link.Po
#	source='source/kernel/link.cc' object='libIris_a-link.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-link.obj `if test -f 'source/kernel/link.cc'; then $(CYGPATH_W) 'source/kernel/link.cc'; else $(CYGPATH_W) '$(srcdir)/source/kernel/link.cc'; fi`

libIris_a-simulator.o: source/kernel/simulator.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-simulator.o -MD -MP -MF $(DEPDIR)/libIris_a-simulator.Tpo -c -o libIris_a-simulator.o `test -f 'source/kernel/simulator.cc' || echo '$(srcdir)/'`source/kernel/simulator.cc
	mv -f $(DEPDIR)/libIris_a-simulator.Tpo $(DEPDIR)/libIris_a-simulator.Po
#	source='source/kernel/simulator.cc' object='libIris_a-simulator.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-simulator.o `test -f 'source/kernel/simulator.cc' || echo '$(srcdir)/'`source/kernel/simulator.cc

libIris_a-simulator.obj: source/kernel/simulator.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-simulator.obj -MD -MP -MF $(DEPDIR)/libIris_a-simulator.Tpo -c -o libIris_a-simulator.obj `if test -f 'source/kernel/simulator.cc'; then $(CYGPATH_W) 'source/kernel/simulator.cc'; else $(CYGPATH_W) '$(srcdir)/source/kernel/simulator.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-simulator.Tpo $(DEPDIR)/libIris_a-simulator.Po
#	source='source/kernel/simulator.cc' object='libIris_a-simulator.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-simulator.obj `if test -f 'source/kernel/simulator.cc'; then $(CYGPATH_W) 'source/kernel/simulator.cc'; else $(CYGPATH_W) '$(srcdir)/source/kernel/simulator.cc'; fi`

libIris_a-component.o: source/kernel/component.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-component.o -MD -MP -MF $(DEPDIR)/libIris_a-component.Tpo -c -o libIris_a-component.o `test -f 'source/kernel/component.cc' || echo '$(srcdir)/'`source/kernel/component.cc
	mv -f $(DEPDIR)/libIris_a-component.Tpo $(DEPDIR)/libIris_a-component.Po
#	source='source/kernel/component.cc' object='libIris_a-component.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-component.o `test -f 'source/kernel/component.cc' || echo '$(srcdir)/'`source/kernel/component.cc

libIris_a-component.obj: source/kernel/component.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-component.obj -MD -MP -MF $(DEPDIR)/libIris_a-component.Tpo -c -o libIris_a-component.obj `if test -f 'source/kernel/component.cc'; then $(CYGPATH_W) 'source/kernel/component.cc'; else $(CYGPATH_W) '$(srcdir)/source/kernel/component.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-component.Tpo $(DEPDIR)/libIris_a-component.Po
#	source='source/kernel/component.cc' object='libIris_a-component.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-component.obj `if test -f 'source/kernel/component.cc'; then $(CYGPATH_W) 'source/kernel/component.cc'; else $(CYGPATH_W) '$(srcdir)/source/kernel/component.cc'; fi`

libIris_a-irisEvent.o: source/data_types/impl/irisEvent.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-irisEvent.o -MD -MP -MF $(DEPDIR)/libIris_a-irisEvent.Tpo -c -o libIris_a-irisEvent.o `test -f 'source/data_types/impl/irisEvent.cc' || echo '$(srcdir)/'`source/data_types/impl/irisEvent.cc
	mv -f $(DEPDIR)/libIris_a-irisEvent.Tpo $(DEPDIR)/libIris_a-irisEvent.Po
#	source='source/data_types/impl/irisEvent.cc' object='libIris_a-irisEvent.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-irisEvent.o `test -f 'source/data_types/impl/irisEvent.cc' || echo '$(srcdir)/'`source/data_types/impl/irisEvent.cc

libIris_a-irisEvent.obj: source/data_types/impl/irisEvent.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-irisEvent.obj -MD -MP -MF $(DEPDIR)/libIris_a-irisEvent.Tpo -c -o libIris_a-irisEvent.obj `if test -f 'source/data_types/impl/irisEvent.cc'; then $(CYGPATH_W) 'source/data_types/impl/irisEvent.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/irisEvent.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-irisEvent.Tpo $(DEPDIR)/libIris_a-irisEvent.Po
#	source='source/data_types/impl/irisEvent.cc' object='libIris_a-irisEvent.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-irisEvent.obj `if test -f 'source/data_types/impl/irisEvent.cc'; then $(CYGPATH_W) 'source/data_types/impl/irisEvent.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/irisEvent.cc'; fi`

libIris_a-flit.o: source/data_types/impl/flit.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-flit.o -MD -MP -MF $(DEPDIR)/libIris_a-flit.Tpo -c -o libIris_a-flit.o `test -f 'source/data_types/impl/flit.cc' || echo '$(srcdir)/'`source/data_types/impl/flit.cc
	mv -f $(DEPDIR)/libIris_a-flit.Tpo $(DEPDIR)/libIris_a-flit.Po
#	source='source/data_types/impl/flit.cc' object='libIris_a-flit.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-flit.o `test -f 'source/data_types/impl/flit.cc' || echo '$(srcdir)/'`source/data_types/impl/flit.cc

libIris_a-flit.obj: source/data_types/impl/flit.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-flit.obj -MD -MP -MF $(DEPDIR)/libIris_a-flit.Tpo -c -o libIris_a-flit.obj `if test -f 'source/data_types/impl/flit.cc'; then $(CYGPATH_W) 'source/data_types/impl/flit.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/flit.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-flit.Tpo $(DEPDIR)/libIris_a-flit.Po
#	source='source/data_types/impl/flit.cc' object='libIris_a-flit.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-flit.obj `if test -f 'source/data_types/impl/flit.cc'; then $(CYGPATH_W) 'source/data_types/impl/flit.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/flit.cc'; fi`

libIris_a-util.o: source/data_types/impl/util.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-util.o -MD -MP -MF $(DEPDIR)/libIris_a-util.Tpo -c -o libIris_a-util.o `test -f 'source/data_types/impl/util.cc' || echo '$(srcdir)/'`source/data_types/impl/util.cc
	mv -f $(DEPDIR)/libIris_a-util.Tpo $(DEPDIR)/libIris_a-util.Po
#	source='source/data_types/impl/util.cc' object='libIris_a-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-util.o `test -f 'source/data_types/impl/util.cc' || echo '$(srcdir)/'`source/data_types/impl/util.cc

libIris_a-util.obj: source/data_types/impl/util.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-util.obj -MD -MP -MF $(DEPDIR)/libIris_a-util.Tpo -c -o libIris_a-util.obj `if test -f 'source/data_types/impl/util.cc'; then $(CYGPATH_W) 'source/data_types/impl/util.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/util.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-util.Tpo $(DEPDIR)/libIris_a-util.Po
#	source='source/data_types/impl/util.cc' object='libIris_a-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-util.obj `if test -f 'source/data_types/impl/util.cc'; then $(CYGPATH_W) 'source/data_types/impl/util.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/util.cc'; fi`

libIris_a-highLevelPacket.o: source/data_types/impl/highLevelPacket.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-highLevelPacket.o -MD -MP -MF $(DEPDIR)/libIris_a-highLevelPacket.Tpo -c -o libIris_a-highLevelPacket.o `test -f 'source/data_types/impl/highLevelPacket.cc' || echo '$(srcdir)/'`source/data_types/impl/highLevelPacket.cc
	mv -f $(DEPDIR)/libIris_a-highLevelPacket.Tpo $(DEPDIR)/libIris_a-highLevelPacket.Po
#	source='source/data_types/impl/highLevelPacket.cc' object='libIris_a-highLevelPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-highLevelPacket.o `test -f 'source/data_types/impl/highLevelPacket.cc' || echo '$(srcdir)/'`source/data_types/impl/highLevelPacket.cc

libIris_a-highLevelPacket.obj: source/data_types/impl/highLevelPacket.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-highLevelPacket.obj -MD -MP -MF $(DEPDIR)/libIris_a-highLevelPacket.Tpo -c -o libIris_a-highLevelPacket.obj `if test -f 'source/data_types/impl/highLevelPacket.cc'; then $(CYGPATH_W) 'source/data_types/impl/highLevelPacket.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/highLevelPacket.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-highLevelPacket.Tpo $(DEPDIR)/libIris_a-highLevelPacket.Po
#	source='source/data_types/impl/highLevelPacket.cc' object='libIris_a-highLevelPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-highLevelPacket.obj `if test -f 'source/data_types/impl/highLevelPacket.cc'; then $(CYGPATH_W) 'source/data_types/impl/highLevelPacket.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/highLevelPacket.cc'; fi`

libIris_a-lowLevelPacket.o: source/data_types/impl/lowLevelPacket.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-lowLevelPacket.o -MD -MP -MF $(DEPDIR)/libIris_a-lowLevelPacket.Tpo -c -o libIris_a-lowLevelPacket.o `test -f 'source/data_types/impl/lowLevelPacket.cc' || echo '$(srcdir)/'`source/data_types/impl/lowLevelPacket.cc
	mv -f $(DEPDIR)/libIris_a-lowLevelPacket.Tpo $(DEPDIR)/libIris_a-lowLevelPacket.Po
#	source='source/data_types/impl/lowLevelPacket.cc' object='libIris_a-lowLevelPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-lowLevelPacket.o `test -f 'source/data_types/impl/lowLevelPacket.cc' || echo '$(srcdir)/'`source/data_types/impl/lowLevelPacket.cc

libIris_a-lowLevelPacket.obj: source/data_types/impl/lowLevelPacket.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-lowLevelPacket.obj -MD -MP -MF $(DEPDIR)/libIris_a-lowLevelPacket.Tpo -c -o libIris_a-lowLevelPacket.obj `if test -f 'source/data_types/impl/lowLevelPacket.cc'; then $(CYGPATH_W) 'source/data_types/impl/lowLevelPacket.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/lowLevelPacket.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-lowLevelPacket.Tpo $(DEPDIR)/libIris_a-lowLevelPacket.Po
#	source='source/data_types/impl/lowLevelPacket.cc' object='libIris_a-lowLevelPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-lowLevelPacket.obj `if test -f 'source/data_types/impl/lowLevelPacket.cc'; then $(CYGPATH_W) 'source/data_types/impl/lowLevelPacket.cc'; else $(CYGPATH_W) '$(srcdir)/source/data_types/impl/lowLevelPacket.cc'; fi`

libIris_a-router.o: source/components/interfaces/router.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-router.o -MD -MP -MF $(DEPDIR)/libIris_a-router.Tpo -c -o libIris_a-router.o `test -f 'source/components/interfaces/router.cc' || echo '$(srcdir)/'`source/components/interfaces/router.cc
	mv -f $(DEPDIR)/libIris_a-router.Tpo $(DEPDIR)/libIris_a-router.Po
#	source='source/components/interfaces/router.cc' object='libIris_a-router.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-router.o `test -f 'source/components/interfaces/router.cc' || echo '$(srcdir)/'`source/components/interfaces/router.cc

libIris_a-router.obj: source/components/interfaces/router.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-router.obj -MD -MP -MF $(DEPDIR)/libIris_a-router.Tpo -c -o libIris_a-router.obj `if test -f 'source/components/interfaces/router.cc'; then $(CYGPATH_W) 'source/components/interfaces/router.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/router.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-router.Tpo $(DEPDIR)/libIris_a-router.Po
#	source='source/components/interfaces/router.cc' object='libIris_a-router.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-router.obj `if test -f 'source/components/interfaces/router.cc'; then $(CYGPATH_W) 'source/components/interfaces/router.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/router.cc'; fi`

libIris_a-processor.o: source/components/interfaces/processor.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-processor.o -MD -MP -MF $(DEPDIR)/libIris_a-processor.Tpo -c -o libIris_a-processor.o `test -f 'source/components/interfaces/processor.cc' || echo '$(srcdir)/'`source/components/interfaces/processor.cc
	mv -f $(DEPDIR)/libIris_a-processor.Tpo $(DEPDIR)/libIris_a-processor.Po
#	source='source/components/interfaces/processor.cc' object='libIris_a-processor.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-processor.o `test -f 'source/components/interfaces/processor.cc' || echo '$(srcdir)/'`source/components/interfaces/processor.cc

libIris_a-processor.obj: source/components/interfaces/processor.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-processor.obj -MD -MP -MF $(DEPDIR)/libIris_a-processor.Tpo -c -o libIris_a-processor.obj `if test -f 'source/components/interfaces/processor.cc'; then $(CYGPATH_W) 'source/components/interfaces/processor.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/processor.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-processor.Tpo $(DEPDIR)/libIris_a-processor.Po
#	source='source/components/interfaces/processor.cc' object='libIris_a-processor.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-processor.obj `if test -f 'source/components/interfaces/processor.cc'; then $(CYGPATH_W) 'source/components/interfaces/processor.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/processor.cc'; fi`

libIris_a-interface.o: source/components/interfaces/interface.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-interface.o -MD -MP -MF $(DEPDIR)/libIris_a-interface.Tpo -c -o libIris_a-interface.o `test -f 'source/components/interfaces/interface.cc' || echo '$(srcdir)/'`source/components/interfaces/interface.cc
	mv -f $(DEPDIR)/libIris_a-interface.Tpo $(DEPDIR)/libIris_a-interface.Po
#	source='source/components/interfaces/interface.cc' object='libIris_a-interface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-interface.o `test -f 'source/components/interfaces/interface.cc' || echo '$(srcdir)/'`source/components/interfaces/interface.cc

libIris_a-interface.obj: source/components/interfaces/interface.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-interface.obj -MD -MP -MF $(DEPDIR)/libIris_a-interface.Tpo -c -o libIris_a-interface.obj `if test -f 'source/components/interfaces/interface.cc'; then $(CYGPATH_W) 'source/components/interfaces/interface.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/interface.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-interface.Tpo $(DEPDIR)/libIris_a-interface.Po
#	source='source/components/interfaces/interface.cc' object='libIris_a-interface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-interface.obj `if test -f 'source/components/interfaces/interface.cc'; then $(CYGPATH_W) 'source/components/interfaces/interface.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/interface.cc'; fi`

libIris_a-irisLink.o: source/components/interfaces/irisLink.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-irisLink.o -MD -MP -MF $(DEPDIR)/libIris_a-irisLink.Tpo -c -o libIris_a-irisLink.o `test -f 'source/components/interfaces/irisLink.cc' || echo '$(srcdir)/'`source/components/interfaces/irisLink.cc
	mv -f $(DEPDIR)/libIris_a-irisLink.Tpo $(DEPDIR)/libIris_a-irisLink.Po
#	source='source/components/interfaces/irisLink.cc' object='libIris_a-irisLink.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-irisLink.o `test -f 'source/components/interfaces/irisLink.cc' || echo '$(srcdir)/'`source/components/interfaces/irisLink.cc

libIris_a-irisLink.obj: source/components/interfaces/irisLink.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-irisLink.obj -MD -MP -MF $(DEPDIR)/libIris_a-irisLink.Tpo -c -o libIris_a-irisLink.obj `if test -f 'source/components/interfaces/irisLink.cc'; then $(CYGPATH_W) 'source/components/interfaces/irisLink.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/irisLink.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-irisLink.Tpo $(DEPDIR)/libIris_a-irisLink.Po
#	source='source/components/interfaces/irisLink.cc' object='libIris_a-irisLink.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-irisLink.obj `if test -f 'source/components/interfaces/irisLink.cc'; then $(CYGPATH_W) 'source/components/interfaces/irisLink.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/irisLink.cc'; fi`

libIris_a-networkComponent.o: source/components/interfaces/networkComponent.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-networkComponent.o -MD -MP -MF $(DEPDIR)/libIris_a-networkComponent.Tpo -c -o libIris_a-networkComponent.o `test -f 'source/components/interfaces/networkComponent.cc' || echo '$(srcdir)/'`source/components/interfaces/networkComponent.cc
	mv -f $(DEPDIR)/libIris_a-networkComponent.Tpo $(DEPDIR)/libIris_a-networkComponent.Po
#	source='source/components/interfaces/networkComponent.cc' object='libIris_a-networkComponent.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-networkComponent.o `test -f 'source/components/interfaces/networkComponent.cc' || echo '$(srcdir)/'`source/components/interfaces/networkComponent.cc

libIris_a-networkComponent.obj: source/components/interfaces/networkComponent.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-networkComponent.obj -MD -MP -MF $(DEPDIR)/libIris_a-networkComponent.Tpo -c -o libIris_a-networkComponent.obj `if test -f 'source/components/interfaces/networkComponent.cc'; then $(CYGPATH_W) 'source/components/interfaces/networkComponent.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/networkComponent.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-networkComponent.Tpo $(DEPDIR)/libIris_a-networkComponent.Po
#	source='source/components/interfaces/networkComponent.cc' object='libIris_a-networkComponent.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-networkComponent.obj `if test -f 'source/components/interfaces/networkComponent.cc'; then $(CYGPATH_W) 'source/components/interfaces/networkComponent.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/interfaces/networkComponent.cc'; fi`

libIris_a-genericBuffer.o: source/components/impl/genericBuffer.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericBuffer.o -MD -MP -MF $(DEPDIR)/libIris_a-genericBuffer.Tpo -c -o libIris_a-genericBuffer.o `test -f 'source/components/impl/genericBuffer.cc' || echo '$(srcdir)/'`source/components/impl/genericBuffer.cc
	mv -f $(DEPDIR)/libIris_a-genericBuffer.Tpo $(DEPDIR)/libIris_a-genericBuffer.Po
#	source='source/components/impl/genericBuffer.cc' object='libIris_a-genericBuffer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericBuffer.o `test -f 'source/components/impl/genericBuffer.cc' || echo '$(srcdir)/'`source/components/impl/genericBuffer.cc

libIris_a-genericBuffer.obj: source/components/impl/genericBuffer.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericBuffer.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericBuffer.Tpo -c -o libIris_a-genericBuffer.obj `if test -f 'source/components/impl/genericBuffer.cc'; then $(CYGPATH_W) 'source/components/impl/genericBuffer.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericBuffer.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericBuffer.Tpo $(DEPDIR)/libIris_a-genericBuffer.Po
#	source='source/components/impl/genericBuffer.cc' object='libIris_a-genericBuffer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericBuffer.obj `if test -f 'source/components/impl/genericBuffer.cc'; then $(CYGPATH_W) 'source/components/impl/genericBuffer.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericBuffer.cc'; fi`

libIris_a-genericRC.o: source/components/impl/genericRC.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericRC.o -MD -MP -MF $(DEPDIR)/libIris_a-genericRC.Tpo -c -o libIris_a-genericRC.o `test -f 'source/components/impl/genericRC.cc' || echo '$(srcdir)/'`source/components/impl/genericRC.cc
	mv -f $(DEPDIR)/libIris_a-genericRC.Tpo $(DEPDIR)/libIris_a-genericRC.Po
#	source='source/components/impl/genericRC.cc' object='libIris_a-genericRC.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericRC.o `test -f 'source/components/impl/genericRC.cc' || echo '$(srcdir)/'`source/components/impl/genericRC.cc

libIris_a-genericRC.obj: source/components/impl/genericRC.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericRC.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericRC.Tpo -c -o libIris_a-genericRC.obj `if test -f 'source/components/impl/genericRC.cc'; then $(CYGPATH_W) 'source/components/impl/genericRC.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericRC.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericRC.Tpo $(DEPDIR)/libIris_a-genericRC.Po
#	source='source/components/impl/genericRC.cc' object='libIris_a-genericRC.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericRC.obj `if test -f 'source/components/impl/genericRC.cc'; then $(CYGPATH_W) 'source/components/impl/genericRC.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericRC.cc'; fi`

libIris_a-genericCrossbar.o: source/components/impl/genericCrossbar.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericCrossbar.o -MD -MP -MF $(DEPDIR)/libIris_a-genericCrossbar.Tpo -c -o libIris_a-genericCrossbar.o `test -f 'source/components/impl/genericCrossbar.cc' || echo '$(srcdir)/'`source/components/impl/genericCrossbar.cc
	mv -f $(DEPDIR)/libIris_a-genericCrossbar.Tpo $(DEPDIR)/libIris_a-genericCrossbar.Po
#	source='source/components/impl/genericCrossbar.cc' object='libIris_a-genericCrossbar.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericCrossbar.o `test -f 'source/components/impl/genericCrossbar.cc' || echo '$(srcdir)/'`source/components/impl/genericCrossbar.cc

libIris_a-genericCrossbar.obj: source/components/impl/genericCrossbar.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericCrossbar.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericCrossbar.Tpo -c -o libIris_a-genericCrossbar.obj `if test -f 'source/components/impl/genericCrossbar.cc'; then $(CYGPATH_W) 'source/components/impl/genericCrossbar.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericCrossbar.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericCrossbar.Tpo $(DEPDIR)/libIris_a-genericCrossbar.Po
#	source='source/components/impl/genericCrossbar.cc' object='libIris_a-genericCrossbar.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericCrossbar.obj `if test -f 'source/components/impl/genericCrossbar.cc'; then $(CYGPATH_W) 'source/components/impl/genericCrossbar.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericCrossbar.cc'; fi`

libIris_a-genericInterface.o: source/components/impl/genericInterface.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericInterface.o -MD -MP -MF $(DEPDIR)/libIris_a-genericInterface.Tpo -c -o libIris_a-genericInterface.o `test -f 'source/components/impl/genericInterface.cc' || echo '$(srcdir)/'`source/components/impl/genericInterface.cc
	mv -f $(DEPDIR)/libIris_a-genericInterface.Tpo $(DEPDIR)/libIris_a-genericInterface.Po
#	source='source/components/impl/genericInterface.cc' object='libIris_a-genericInterface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericInterface.o `test -f 'source/components/impl/genericInterface.cc' || echo '$(srcdir)/'`source/components/impl/genericInterface.cc

libIris_a-genericInterface.obj: source/components/impl/genericInterface.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericInterface.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericInterface.Tpo -c -o libIris_a-genericInterface.obj `if test -f 'source/components/impl/genericInterface.cc'; then $(CYGPATH_W) 'source/components/impl/genericInterface.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericInterface.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericInterface.Tpo $(DEPDIR)/libIris_a-genericInterface.Po
#	source='source/components/impl/genericInterface.cc' object='libIris_a-genericInterface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericInterface.obj `if test -f 'source/components/impl/genericInterface.cc'; then $(CYGPATH_W) 'source/components/impl/genericInterface.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericInterface.cc'; fi`

libIris_a-genericData.o: source/components/impl/genericData.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericData.o -MD -MP -MF $(DEPDIR)/libIris_a-genericData.Tpo -c -o libIris_a-genericData.o `test -f 'source/components/impl/genericData.cc' || echo '$(srcdir)/'`source/components/impl/genericData.cc
	mv -f $(DEPDIR)/libIris_a-genericData.Tpo $(DEPDIR)/libIris_a-genericData.Po
#	source='source/components/impl/genericData.cc' object='libIris_a-genericData.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericData.o `test -f 'source/components/impl/genericData.cc' || echo '$(srcdir)/'`source/components/impl/genericData.cc

libIris_a-genericData.obj: source/components/impl/genericData.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericData.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericData.Tpo -c -o libIris_a-genericData.obj `if test -f 'source/components/impl/genericData.cc'; then $(CYGPATH_W) 'source/components/impl/genericData.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericData.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericData.Tpo $(DEPDIR)/libIris_a-genericData.Po
#	source='source/components/impl/genericData.cc' object='libIris_a-genericData.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericData.obj `if test -f 'source/components/impl/genericData.cc'; then $(CYGPATH_W) 'source/components/impl/genericData.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericData.cc'; fi`

libIris_a-genericLink.o: source/components/impl/genericLink.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericLink.o -MD -MP -MF $(DEPDIR)/libIris_a-genericLink.Tpo -c -o libIris_a-genericLink.o `test -f 'source/components/impl/genericLink.cc' || echo '$(srcdir)/'`source/components/impl/genericLink.cc
	mv -f $(DEPDIR)/libIris_a-genericLink.Tpo $(DEPDIR)/libIris_a-genericLink.Po
#	source='source/components/impl/genericLink.cc' object='libIris_a-genericLink.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericLink.o `test -f 'source/components/impl/genericLink.cc' || echo '$(srcdir)/'`source/components/impl/genericLink.cc

libIris_a-genericLink.obj: source/components/impl/genericLink.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericLink.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericLink.Tpo -c -o libIris_a-genericLink.obj `if test -f 'source/components/impl/genericLink.cc'; then $(CYGPATH_W) 'source/components/impl/genericLink.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericLink.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericLink.Tpo $(DEPDIR)/libIris_a-genericLink.Po
#	source='source/components/impl/genericLink.cc' object='libIris_a-genericLink.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericLink.obj `if test -f 'source/components/impl/genericLink.cc'; then $(CYGPATH_W) 'source/components/impl/genericLink.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericLink.cc'; fi`

libIris_a-ptop_swa.o: source/components/impl/ptop_swa.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-ptop_swa.o -MD -MP -MF $(DEPDIR)/libIris_a-ptop_swa.Tpo -c -o libIris_a-ptop_swa.o `test -f 'source/components/impl/ptop_swa.cc' || echo '$(srcdir)/'`source/components/impl/ptop_swa.cc
	mv -f $(DEPDIR)/libIris_a-ptop_swa.Tpo $(DEPDIR)/libIris_a-ptop_swa.Po
#	source='source/components/impl/ptop_swa.cc' object='libIris_a-ptop_swa.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-ptop_swa.o `test -f 'source/components/impl/ptop_swa.cc' || echo '$(srcdir)/'`source/components/impl/ptop_swa.cc

libIris_a-ptop_swa.obj: source/components/impl/ptop_swa.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-ptop_swa.obj -MD -MP -MF $(DEPDIR)/libIris_a-ptop_swa.Tpo -c -o libIris_a-ptop_swa.obj `if test -f 'source/components/impl/ptop_swa.cc'; then $(CYGPATH_W) 'source/components/impl/ptop_swa.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/ptop_swa.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-ptop_swa.Tpo $(DEPDIR)/libIris_a-ptop_swa.Po
#	source='source/components/impl/ptop_swa.cc' object='libIris_a-ptop_swa.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-ptop_swa.obj `if test -f 'source/components/impl/ptop_swa.cc'; then $(CYGPATH_W) 'source/components/impl/ptop_swa.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/ptop_swa.cc'; fi`

libIris_a-genericRouterNoVcs.o: source/components/impl/genericRouterNoVcs.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericRouterNoVcs.o -MD -MP -MF $(DEPDIR)/libIris_a-genericRouterNoVcs.Tpo -c -o libIris_a-genericRouterNoVcs.o `test -f 'source/components/impl/genericRouterNoVcs.cc' || echo '$(srcdir)/'`source/components/impl/genericRouterNoVcs.cc
	mv -f $(DEPDIR)/libIris_a-genericRouterNoVcs.Tpo $(DEPDIR)/libIris_a-genericRouterNoVcs.Po
#	source='source/components/impl/genericRouterNoVcs.cc' object='libIris_a-genericRouterNoVcs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericRouterNoVcs.o `test -f 'source/components/impl/genericRouterNoVcs.cc' || echo '$(srcdir)/'`source/components/impl/genericRouterNoVcs.cc

libIris_a-genericRouterNoVcs.obj: source/components/impl/genericRouterNoVcs.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericRouterNoVcs.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericRouterNoVcs.Tpo -c -o libIris_a-genericRouterNoVcs.obj `if test -f 'source/components/impl/genericRouterNoVcs.cc'; then $(CYGPATH_W) 'source/components/impl/genericRouterNoVcs.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericRouterNoVcs.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericRouterNoVcs.Tpo $(DEPDIR)/libIris_a-genericRouterNoVcs.Po
#	source='source/components/impl/genericRouterNoVcs.cc' object='libIris_a-genericRouterNoVcs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericRouterNoVcs.obj `if test -f 'source/components/impl/genericRouterNoVcs.cc'; then $(CYGPATH_W) 'source/components/impl/genericRouterNoVcs.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericRouterNoVcs.cc'; fi`

libIris_a-genericRouterVct.o: source/components/impl/genericRouterVct.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericRouterVct.o -MD -MP -MF $(DEPDIR)/libIris_a-genericRouterVct.Tpo -c -o libIris_a-genericRouterVct.o `test -f 'source/components/impl/genericRouterVct.cc' || echo '$(srcdir)/'`source/components/impl/genericRouterVct.cc
	mv -f $(DEPDIR)/libIris_a-genericRouterVct.Tpo $(DEPDIR)/libIris_a-genericRouterVct.Po
#	source='source/components/impl/genericRouterVct.cc' object='libIris_a-genericRouterVct.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericRouterVct.o `test -f 'source/components/impl/genericRouterVct.cc' || echo '$(srcdir)/'`source/components/impl/genericRouterVct.cc

libIris_a-genericRouterVct.obj: source/components/impl/genericRouterVct.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericRouterVct.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericRouterVct.Tpo -c -o libIris_a-genericRouterVct.obj `if test -f 'source/components/impl/genericRouterVct.cc'; then $(CYGPATH_W) 'source/components/impl/genericRouterVct.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericRouterVct.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericRouterVct.Tpo $(DEPDIR)/libIris_a-genericRouterVct.Po
#	source='source/components/impl/genericRouterVct.cc' object='libIris_a-genericRouterVct.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericRouterVct.obj `if test -f 'source/components/impl/genericRouterVct.cc'; then $(CYGPATH_W) 'source/components/impl/genericRouterVct.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericRouterVct.cc'; fi`

libIris_a-genericFlatMc.o: source/components/impl/genericFlatMc.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericFlatMc.o -MD -MP -MF $(DEPDIR)/libIris_a-genericFlatMc.Tpo -c -o libIris_a-genericFlatMc.o `test -f 'source/components/impl/genericFlatMc.cc' || echo '$(srcdir)/'`source/components/impl/genericFlatMc.cc
	mv -f $(DEPDIR)/libIris_a-genericFlatMc.Tpo $(DEPDIR)/libIris_a-genericFlatMc.Po
#	source='source/components/impl/genericFlatMc.cc' object='libIris_a-genericFlatMc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericFlatMc.o `test -f 'source/components/impl/genericFlatMc.cc' || echo '$(srcdir)/'`source/components/impl/genericFlatMc.cc

libIris_a-genericFlatMc.obj: source/components/impl/genericFlatMc.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericFlatMc.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericFlatMc.Tpo -c -o libIris_a-genericFlatMc.obj `if test -f 'source/components/impl/genericFlatMc.cc'; then $(CYGPATH_W) 'source/components/impl/genericFlatMc.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericFlatMc.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericFlatMc.Tpo $(DEPDIR)/libIris_a-genericFlatMc.Po
#	source='source/components/impl/genericFlatMc.cc' object='libIris_a-genericFlatMc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericFlatMc.obj `if test -f 'source/components/impl/genericFlatMc.cc'; then $(CYGPATH_W) 'source/components/impl/genericFlatMc.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericFlatMc.cc'; fi`

libIris_a-genericTPG.o: source/components/impl/genericTPG.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericTPG.o -MD -MP -MF $(DEPDIR)/libIris_a-genericTPG.Tpo -c -o libIris_a-genericTPG.o `test -f 'source/components/impl/genericTPG.cc' || echo '$(srcdir)/'`source/components/impl/genericTPG.cc
	mv -f $(DEPDIR)/libIris_a-genericTPG.Tpo $(DEPDIR)/libIris_a-genericTPG.Po
#	source='source/components/impl/genericTPG.cc' object='libIris_a-genericTPG.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericTPG.o `test -f 'source/components/impl/genericTPG.cc' || echo '$(srcdir)/'`source/components/impl/genericTPG.cc

libIris_a-genericTPG.obj: source/components/impl/genericTPG.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-genericTPG.obj -MD -MP -MF $(DEPDIR)/libIris_a-genericTPG.Tpo -c -o libIris_a-genericTPG.obj `if test -f 'source/components/impl/genericTPG.cc'; then $(CYGPATH_W) 'source/components/impl/genericTPG.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericTPG.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-genericTPG.Tpo $(DEPDIR)/libIris_a-genericTPG.Po
#	source='source/components/impl/genericTPG.cc' object='libIris_a-genericTPG.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-genericTPG.obj `if test -f 'source/components/impl/genericTPG.cc'; then $(CYGPATH_W) 'source/components/impl/genericTPG.cc'; else $(CYGPATH_W) '$(srcdir)/source/components/impl/genericTPG.cc'; fi`

libIris_a-mshr.o: source/memctrl/mshr.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-mshr.o -MD -MP -MF $(DEPDIR)/libIris_a-mshr.Tpo -c -o libIris_a-mshr.o `test -f 'source/memctrl/mshr.cc' || echo '$(srcdir)/'`source/memctrl/mshr.cc
	mv -f $(DEPDIR)/libIris_a-mshr.Tpo $(DEPDIR)/libIris_a-mshr.Po
#	source='source/memctrl/mshr.cc' object='libIris_a-mshr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-mshr.o `test -f 'source/memctrl/mshr.cc' || echo '$(srcdir)/'`source/memctrl/mshr.cc

libIris_a-mshr.obj: source/memctrl/mshr.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-mshr.obj -MD -MP -MF $(DEPDIR)/libIris_a-mshr.Tpo -c -o libIris_a-mshr.obj `if test -f 'source/memctrl/mshr.cc'; then $(CYGPATH_W) 'source/memctrl/mshr.cc'; else $(CYGPATH_W) '$(srcdir)/source/memctrl/mshr.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-mshr.Tpo $(DEPDIR)/libIris_a-mshr.Po
#	source='source/memctrl/mshr.cc' object='libIris_a-mshr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-mshr.obj `if test -f 'source/memctrl/mshr.cc'; then $(CYGPATH_W) 'source/memctrl/mshr.cc'; else $(CYGPATH_W) '$(srcdir)/source/memctrl/mshr.cc'; fi`

libIris_a-request.o: source/memctrl/request.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-request.o -MD -MP -MF $(DEPDIR)/libIris_a-request.Tpo -c -o libIris_a-request.o `test -f 'source/memctrl/request.cc' || echo '$(srcdir)/'`source/memctrl/request.cc
	mv -f $(DEPDIR)/libIris_a-request.Tpo $(DEPDIR)/libIris_a-request.Po
#	source='source/memctrl/request.cc' object='libIris_a-request.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-request.o `test -f 'source/memctrl/request.cc' || echo '$(srcdir)/'`source/memctrl/request.cc

libIris_a-request.obj: source/memctrl/request.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-request.obj -MD -MP -MF $(DEPDIR)/libIris_a-request.Tpo -c -o libIris_a-request.obj `if test -f 'source/memctrl/request.cc'; then $(CYGPATH_W) 'source/memctrl/request.cc'; else $(CYGPATH_W) '$(srcdir)/source/memctrl/request.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-request.Tpo $(DEPDIR)/libIris_a-request.Po
#	source='source/memctrl/request.cc' object='libIris_a-request.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-request.obj `if test -f 'source/memctrl/request.cc'; then $(CYGPATH_W) 'source/memctrl/request.cc'; else $(CYGPATH_W) '$(srcdir)/source/memctrl/request.cc'; fi`

libIris_a-mesh.o: source/frontend/impl/mesh.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-mesh.o -MD -MP -MF $(DEPDIR)/libIris_a-mesh.Tpo -c -o libIris_a-mesh.o `test -f 'source/frontend/impl/mesh.cc' || echo '$(srcdir)/'`source/frontend/impl/mesh.cc
	mv -f $(DEPDIR)/libIris_a-mesh.Tpo $(DEPDIR)/libIris_a-mesh.Po
#	source='source/frontend/impl/mesh.cc' object='libIris_a-mesh.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-mesh.o `test -f 'source/frontend/impl/mesh.cc' || echo '$(srcdir)/'`source/frontend/impl/mesh.cc

libIris_a-mesh.obj: source/frontend/impl/mesh.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -MT libIris_a-mesh.obj -MD -MP -MF $(DEPDIR)/libIris_a-mesh.Tpo -c -o libIris_a-mesh.obj `if test -f 'source/frontend/impl/mesh.cc'; then $(CYGPATH_W) 'source/frontend/impl/mesh.cc'; else $(CYGPATH_W) '$(srcdir)/source/frontend/impl/mesh.cc'; fi`
	mv -f $(DEPDIR)/libIris_a-mesh.Tpo $(DEPDIR)/libIris_a-mesh.Po
#	source='source/frontend/impl/mesh.cc' object='libIris_a-mesh.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libIris_a_CXXFLAGS) $(CXXFLAGS) -c -o libIris_a-mesh.obj `if test -f 'source/frontend/impl/mesh.cc'; then $(CYGPATH_W) 'source/frontend/impl/mesh.cc'; else $(CYGPATH_W) '$(srcdir)/source/frontend/impl/mesh.cc'; fi`

simMc2Mesh-simMc2Mesh.o: source/frontend/impl/simMc2Mesh.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(simMc2Mesh_CXXFLAGS) $(CXXFLAGS) -MT simMc2Mesh-simMc2Mesh.o -MD -MP -MF $(DEPDIR)/simMc2Mesh-simMc2Mesh.Tpo -c -o simMc2Mesh-simMc2Mesh.o `test -f 'source/frontend/impl/simMc2Mesh.cc' || echo '$(srcdir)/'`source/frontend/impl/simMc2Mesh.cc
	mv -f $(DEPDIR)/simMc2Mesh-simMc2Mesh.Tpo $(DEPDIR)/simMc2Mesh-simMc2Mesh.Po
#	source='source/frontend/impl/simMc2Mesh.cc' object='simMc2Mesh-simMc2Mesh.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(simMc2Mesh_CXXFLAGS) $(CXXFLAGS) -c -o simMc2Mesh-simMc2Mesh.o `test -f 'source/frontend/impl/simMc2Mesh.cc' || echo '$(srcdir)/'`source/frontend/impl/simMc2Mesh.cc

simMc2Mesh-simMc2Mesh.obj: source/frontend/impl/simMc2Mesh.cc
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(simMc2Mesh_CXXFLAGS) $(CXXFLAGS) -MT simMc2Mesh-simMc2Mesh.obj -MD -MP -MF $(DEPDIR)/simMc2Mesh-simMc2Mesh.Tpo -c -o simMc2Mesh-simMc2Mesh.obj `if test -f 'source/frontend/impl/simMc2Mesh.cc'; then $(CYGPATH_W) 'source/frontend/impl/simMc2Mesh.cc'; else $(CYGPATH_W) '$(srcdir)/source/frontend/impl/simMc2Mesh.cc'; fi`
	mv -f $(DEPDIR)/simMc2Mesh-simMc2Mesh.Tpo $(DEPDIR)/simMc2Mesh-simMc2Mesh.Po
#	source='source/frontend/impl/simMc2Mesh.cc' object='simMc2Mesh-simMc2Mesh.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(simMc2Mesh_CXXFLAGS) $(CXXFLAGS) -c -o simMc2Mesh-simMc2Mesh.obj `if test -f 'source/frontend/impl/simMc2Mesh.cc'; then $(CYGPATH_W) 'source/frontend/impl/simMc2Mesh.cc'; else $(CYGPATH_W) '$(srcdir)/source/frontend/impl/simMc2Mesh.cc'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-noinstLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-info: install-info-am

install-man:

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-noinstLIBRARIES ctags \
	dist dist-all dist-bzip2 dist-gzip dist-lzma dist-shar \
	dist-tarZ dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
